project:
  type: website
  output-dir: docs

website:
  title: "Adrian's races"
  navbar:
    left:
      - href: main.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
